FROM mysql:8.0
# Default env variable reference avalaible in DockerHub MYSQL_ROOT_PASSWORD is used to set the root password for MySQL.
ENV MYSQL_ROOT_PASSWORD="RoboShop@1"
COPY db/ /docker-entrypoint-initdb.d